proto-order-server:
	protoc -I ./proto \
    --go_out ./order/internal/adapters/grpc/generated/orders \
    --go_opt paths=source_relative \
    --go-grpc_out ./order/internal/adapters/grpc/generated/orders \
    --go-grpc_opt paths=source_relative \
    ./proto/order.proto

proto-payment-server:
	protoc -I ./proto \
    --go_out ./payment/internal/adapters/grpc/generated/payment \
    --go_opt paths=source_relative \
    --go-grpc_out ./payment/internal/adapters/grpc/generated/payment \
    --go-grpc_opt paths=source_relative \
    ./proto/payment.proto

proto-payment-client:
	protoc -I ./proto \
    --go_out ./order/internal/adapters/grpc/generated/payments \
    --go_opt paths=source_relative \
    --go-grpc_out ./order/internal/adapters/grpc/generated/payments \
    --go-grpc_opt paths=source_relative \
    ./proto/payment.proto

start-db:
	docker run --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres