proto-order:
	protoc -I ./proto \
    --go_out ./order/internal/adapters/grpc/generated \
    --go_opt paths=source_relative \
    --go-grpc_out ./order/internal/adapters/grpc/generated \
    --go-grpc_opt paths=source_relative \
    ./proto/order.proto

proto-payment:
	protoc -I ./proto \
    --go_out ./payment/internal/adapters/grpc/generated \
    --go_opt paths=source_relative \
    --go-grpc_out ./payment/internal/adapters/grpc/generated \
    --go-grpc_opt paths=source_relative \
    ./proto/payment.proto

start-db:
	docker run --name some-postgres -p 5432:5432 -e POSTGRES_PASSWORD=postgres -d postgres